apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: k8s-service-capability
  name: k8s-service-capability
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-service-package-noop
  namespace: k8s-service-capability
data:
  noop: "true"