apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: deployment-capability
  name: deployment-capability
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-package-noop
  namespace: deployment-capability
data:
  noop: "true"