apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    capability.tanzu.vmware.com/provides: |
      [{ "name": "k8s-service-capability.tanzu.japan.com",
         "displayName": "K8s Capability",
         "vendor": "VMware Tanzu",
         "description": "Allows creating k8s service in space",
         "tags":["apps"],
         "groupVersionKinds": [
           { "apiVersion": "v1", "kind": "Service" }
         ]
       }
      ]
  name: k8s-service-capability.tanzu.japan.com.0.0.1
spec:
  refName: k8s-service-capability.tanzu.japan.com
  version: 0.0.1
  valuesSchema:
    openAPIv3:
      title: k8s-service-capability.tanzu-jp values schema
  template:
    spec:
      fetch:
        - git:
            url: https://github.com/mhoshi-vm/tp-k8s-service-from-space
            ref: origin/main
            subPath: manifests/
      template:
        - ytt: {}
      deploy:
        - kapp: {}